site_name: Attendance & Employee Management API
theme:
  name: material  # Optional, but highly recommended for a clean UI
nav:
  - Home: index.md
  - API Documentation: api-documentation.md
  - Endpoints : endpoints.md
  - Developer's guide : developer-guide.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.mark